name: optisplat
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.12
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pytorch-cuda=11.6
  - tqdm
  - tensorboard
  - pip:
    - submodules/diff-gaussian-rasterization-pinhole
    - submodules/simple-knn
    - submodules/fused-ssim
